export const GET_SESI_REQUEST = 'GET_SESI_REQUEST';
export const GET_SESI_SUCCESS = 'GET_SESI_SUCCESS';
export const GET_SESI_FAILURE = 'GET_SESI_FAILURE';

export const UPDATE_SESI_REQUEST = 'UPDATE_SESI_REQUEST';
export const UPDATE_SESI_SUCCESS = 'UPDATE_SESI_SUCCESS';
export const UPDATE_SESI_FAILURE = 'UPDATE_SESI_FAILURE';

export const CLEAR_SESI = 'CLEAR_SESI';
